namespace StrangeSharpTerm.Security.Tests;

/// <summary>
/// Keys and a hashed line generated by ssh-keygen, so the parser is checked
/// against what OpenSSH actually writes rather than against an invented format.
/// </summary>
internal static class Fixture
{
    public const string KeyTypeA = "ssh-ed25519";
    public const string KeyA = "AAAAC3NzaC1lZDI1NTE5AAAAILejjnprMAZ8uimAGj0FMm415xZa55WMGkUiKVKlio8z";
    public const string KeyTypeB = "ssh-rsa";
    public const string KeyB = "AAAAB3NzaC1yc2EAAAADAQABAAABAQCavcmspPeehEPOY/pjYbpHl8H74X9w4/o4FQ6FZ092AX80UYH6ALw32ZP0B/9FT2vV0qtBw3856gA5u3OZC4jDYF+kdOqm1grToCJsUEcNwfWHlJaukXUpa3KUIjIRC43SXba9Gi5jTt16xY8+i66vQuW7/yqKuZBSPLFbeXlJLbO9CXSEPEb+DvTrnwakEAlR7wYSXMwuBgKP/CNHkwS2KN4PSfFoZp1r3IT2Y43xnTc6Iggw+PY7BdEWlzAuqhb9icxFSog2XrqcNXBg15xRVQrHPPeKfqBmvooRgcb9MK+gdfIRAFI+qaOS8q7ELjtBOhsrUeSyCJY7xFiEtV7l";
    public const string HashedLine = "|1|QzfBPmv92ejPXrjw/G4aFUE7+2Y=|SKUChnV4MAqqlNER/Yg63YkTarM= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILejjnprMAZ8uimAGj0FMm415xZa55WMGkUiKVKlio8z";

    /// <summary>What <c>ssh-keygen -lf</c> reports for <see cref="KeyA"/>.</summary>
    public const string FingerprintA = "SHA256:iVhZqYCmBVZIqh6rtLy6Wh1sq6okkt5Nuynx93rFRzk";

    public const string Plain = $"""
        example.com {KeyTypeA} {KeyA}
        [example.com]:2222 {KeyTypeA} {KeyA}
        @revoked bad.example.com {KeyTypeB} {KeyB}
        """;
}

public class KnownHostsParsingTests
{
    [Fact]
    public void BlankLinesAndCommentsAreSkipped()
    {
        KnownHostsFile.Parse($"\n# a comment\n\n{Fixture.Plain}").Entries.Count.ShouldBe(3);
    }

    [Fact]
    public void MarkersAreRecognised()
    {
        var entries = KnownHostsFile.Parse(Fixture.Plain).Entries;
        entries[0].Marker.ShouldBeNull();
        entries[2].Marker.ShouldBe(KnownHostMarker.Revoked);
    }

    [Fact]
    public void ATrailingCommentDoesNotBreakTheLine()
    {
        var entries = KnownHostsFile.Parse($"example.com {Fixture.KeyTypeA} {Fixture.KeyA} me@laptop").Entries;
        entries.Count.ShouldBe(1);
        entries[0].KeyBase64.ShouldBe(Fixture.KeyA);
    }

    [Fact]
    public void AMalformedLineIsDroppedRatherThanHalfParsed()
    {
        KnownHostsFile.Parse("example.com ssh-ed25519").Entries.ShouldBeEmpty();
    }

    [Fact]
    public void OurFingerprintMatchesWhatSshKeygenReports()
    {
        // The whole point of showing a fingerprint is that the user can compare it
        // with one from another source; a different encoding would be useless.
        KnownHostsFile.Parse(Fixture.Plain).Entries[0].Fingerprint.ShouldBe(Fixture.FingerprintA);
    }

    [Fact]
    public void WindowsLineEndingsDoNotCorruptTheKey()
    {
        // A known_hosts file edited on Windows ends its lines with CRLF; a stray
        // carriage return on the key would make every comparison fail.
        var entries = KnownHostsFile.Parse($"example.com {Fixture.KeyTypeA} {Fixture.KeyA}\r\n").Entries;
        entries.Count.ShouldBe(1);
        entries[0].KeyBase64.ShouldBe(Fixture.KeyA);
    }
}

public class KnownHostsMatchingTests
{
    private readonly KnownHostsFile _file = KnownHostsFile.Parse(Fixture.Plain);

    [Fact]
    public void AStoredKeyForTheHostIsRecognised()
    {
        _file.Verdict("example.com", 22, Fixture.KeyTypeA, Fixture.KeyA).ShouldBeOfType<HostKeyVerdict.Known>();
    }

    [Fact]
    public void AHostWithNoEntryIsUnknownNotAFailure()
    {
        _file.Verdict("other.example.com", 22, Fixture.KeyTypeA, Fixture.KeyA).ShouldBeOfType<HostKeyVerdict.Unknown>();
    }

    [Fact]
    public void ADifferentKeyForAKnownHostIsChangedWithTheStoredFingerprint()
    {
        // The user has to be shown what was expected, not merely told something is wrong.
        _file.Verdict("example.com", 22, Fixture.KeyTypeA, Fixture.KeyB)
            .ShouldBeOfType<HostKeyVerdict.Changed>()
            .StoredFingerprint.ShouldBe(Fixture.FingerprintA);
    }

    [Fact]
    public void AKeyOfATypeNeverStoredIsUnknownNotChanged()
    {
        // Servers offer several host keys. Having only the Ed25519 one on file says
        // nothing about the RSA one, and calling that an attack would train people
        // to click through real warnings.
        _file.Verdict("example.com", 22, Fixture.KeyTypeB, Fixture.KeyB).ShouldBeOfType<HostKeyVerdict.Unknown>();
    }

    [Fact]
    public void ARevokedKeyIsReportedAsRevoked()
    {
        _file.Verdict("bad.example.com", 22, Fixture.KeyTypeB, Fixture.KeyB).ShouldBeOfType<HostKeyVerdict.Revoked>();
    }

    [Fact]
    public void ANonDefaultPortIsMatchedInBracketForm()
    {
        KnownHostsFile.HostPattern("example.com", 2222).ShouldBe("[example.com]:2222");
        KnownHostsFile.HostPattern("example.com", 22).ShouldBe("example.com");

        _file.Verdict("example.com", 2222, Fixture.KeyTypeA, Fixture.KeyA).ShouldBeOfType<HostKeyVerdict.Known>();
    }

    [Fact]
    public void AHashedEntryWrittenBySshKeygenIsMatched()
    {
        // OpenSSH hashes host names by default, so a parser that only handled plain
        // names would find nothing in most real files.
        var file = KnownHostsFile.Parse(Fixture.HashedLine);
        file.Entries.Count.ShouldBe(1);
        file.Entries[0].IsHashed.ShouldBeTrue();
        file.EntriesMatching("example.com", 22).Count.ShouldBe(1);
    }

    [Fact]
    public void AHashedEntryDoesNotMatchADifferentHost()
    {
        KnownHostsFile.Parse(Fixture.HashedLine).EntriesMatching("elsewhere.example.com", 22).ShouldBeEmpty();
    }

    [Fact]
    public void WildcardPatternsAreHonoured()
    {
        var file = KnownHostsFile.Parse($"*.internal {Fixture.KeyTypeA} {Fixture.KeyA}");
        file.EntriesMatching("db.internal", 22).Count.ShouldBe(1);
        file.EntriesMatching("db.example.com", 22).ShouldBeEmpty();
    }
}

public class KnownHostsWriterTests : IDisposable
{
    private readonly string _directory = Path.Combine(Path.GetTempPath(), $"st-hosts-{Guid.NewGuid():N}");

    public void Dispose()
    {
        if (Directory.Exists(_directory))
            Directory.Delete(_directory, recursive: true);
    }

    [Fact]
    public void AnAcceptedKeyIsWrittenInOpenSshsOwnFormatAndReadsBackAsKnown()
    {
        var path = Path.Combine(_directory, "known_hosts");
        new KnownHostsWriter(path).Append("example.com", 22, Fixture.KeyTypeA, Fixture.KeyA);

        File.ReadAllText(path).ShouldBe($"example.com {Fixture.KeyTypeA} {Fixture.KeyA}\n");
        KnownHostsFile.Read(path).Verdict("example.com", 22, Fixture.KeyTypeA, Fixture.KeyA)
            .ShouldBeOfType<HostKeyVerdict.Known>();
    }

    [Fact]
    public void AppendingKeepsWhatWasAlreadyThere()
    {
        // The file is shared with ssh itself: rewriting it could drop entries added
        // by anything else between our read and our write.
        var path = Path.Combine(_directory, "known_hosts");
        var writer = new KnownHostsWriter(path);
        writer.Append("first.example.com", 22, Fixture.KeyTypeA, Fixture.KeyA);
        writer.Append("second.example.com", 2222, Fixture.KeyTypeA, Fixture.KeyA);

        var file = KnownHostsFile.Read(path);
        file.Entries.Count.ShouldBe(2);
        file.Verdict("second.example.com", 2222, Fixture.KeyTypeA, Fixture.KeyA).ShouldBeOfType<HostKeyVerdict.Known>();
    }

    [Fact]
    public void ANewFileIsReadableOnlyByItsOwner()
    {
        // ssh ignores a known_hosts file that others can write.
        if (!OperatingSystem.IsWindows())
        {
            var path = Path.Combine(_directory, "known_hosts");
            new KnownHostsWriter(path).Append("example.com", 22, Fixture.KeyTypeA, Fixture.KeyA);

            File.GetUnixFileMode(path).ShouldBe(UnixFileMode.UserRead | UnixFileMode.UserWrite);
            File.GetUnixFileMode(_directory)
                .ShouldBe(UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);
            return;
        }

        Assert.Skip("Windows has no POSIX mode bits; the file inherits the profile directory's ACL.");
    }

    [Fact]
    public void TheDefaultPathIsTheOneSshItselfUses()
    {
        KnownHostsWriter.DefaultPath().ShouldBe(Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".ssh", "known_hosts"));
    }
}
